version: 1
jobs:
  compile:
    image: node
    script:
      - npm install truffle
      - npx truffle compile
  test:
    image: node
    script:
      - npm install truffle
      - npx truffle test
  deploy_to_rinkeby:
    image: node
    type:
      name: ethereum/deploy
      script:
        - npm install
        - npx truffle migrate --network rinkeby_metamask --reset
        - npx superblocks-cli collect-artifacts

stages:
  - build_and_test:
      jobs:
        - compile
        # - test
  - deploy_to_testnet:
      jobs:
        - deploy_to_rinkeby
            when: manual
                filters:
                  only: 
                    - master